=== lollofrancescotti/progetto_linguaggi/Tesina linguaggi per il web/xml/requests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="requests">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="request" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="importo" type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="status" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== lollofrancescotti/progetto_linguaggi/Tesina linguaggi per il web/xml/requests.xml
<?xml version="1.0" encoding="UTF-8"?>
<requests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="requests.xsd">
  <request status="Rifiutato">
    <email>fede@gmail.com</email>
    <importo>555</importo>
  </request>
  <request status="Rifiutato">
    <email>fede@gmail.com</email>
    <importo>-15210</importo>
  </request>
  <request status="Rifiutato">
    <email>fede@gmail.com</email>
    <importo>100</importo>
  </request>
</requests>
