=== lollofrancescotti/progetto_linguaggi/Tesina linguaggi per il web/xml/storico_acquisti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="acquisti">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="acquisto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="data" type="xs:date"/>
              <xs:element name="ora" type="xs:time"/>
              <xs:element name="id_prodotto" type="xs:integer"/>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="prezzo_unitario" type="xs:decimal"/>
              <xs:element name="quantita" type="xs:integer"/>
              <xs:element name="prezzo_scontato" type="xs:decimal"/>
              <xs:element name="bonus" type="xs:integer" minOccurs="0"/>
              <xs:element name="prezzo_totale" type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="id_utente" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== lollofrancescotti/progetto_linguaggi/Tesina linguaggi per il web/xml/storico_acquisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<acquisti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storico_acquisti.xsd">
  
<acquisto id_utente="5"><data>2024-03-11</data><ora>20:39:14</ora><id_prodotto>7</id_prodotto><nome>Maglia Rugby Australia 2022-2023</nome><prezzo_unitario>60</prezzo_unitario><quantita>1</quantita><prezzo_scontato>57.60</prezzo_scontato><bonus>0</bonus><prezzo_totale>57.6</prezzo_totale></acquisto><acquisto id_utente="5"><data>2024-03-11</data><ora>20:39:14</ora><id_prodotto>5</id_prodotto><nome>Pantaloncini Rugby Italia 2022-2023</nome><prezzo_unitario>30</prezzo_unitario><quantita>1</quantita><prezzo_scontato>28.80</prezzo_scontato><bonus>0</bonus><prezzo_totale>28.8</prezzo_totale></acquisto></acquisti>
